config/routes.rb
PeerReviewer::Application.routes.draw do
  root :to => 'sessions#new'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  resources :reviews
  resources :sessions
  resources :users
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :password, :presence => {:on => :create}

  def self.authenticate_for_username(username, password)
    user = self.where("username = ?", username).first.try(:authenticate, password)
    user.nil? ? false : user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find_by_id params[:id]
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new params[:review]
    if @review.save
      redirect_to reviews_path, notice: "The review was created!"
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'

  def new
  end

  def create
    user = User.authenticate_for_username(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to reviews_path
    else
      flash.now.alert = "Invalid username or password. Please try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to users_path, notice: "User was successfully created!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_menu.html.erb
<% if current_user %>
  Welcome, <%= current_user.username %>
  <%= link_to "Users", users_path %>
  <%= link_to "Reviews", reviews_path %>
  <%= link_to "Logout", logout_path %>
<% else %>
  <%= link_to "Login", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peer Reviewer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="prepend-1 span-10">
      <%= link_to "Home", root_path %>
    </div>

    <div class="append-1 span-12 last">
      <div id="user_nav">
        <%= render :partial => 'menu' %>
      </div>
    </div>

    <div class="prepend-1 span-22 append-1">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash#{name}", class: "#{name}" %>
      <% end %>
    </div>

    <div class="prepend-1 span-22 append-1">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peer Reviewer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="login_container" class="container">
    <div class="column prepend-8">&nbsp;</div>
    <div class="span-8">
      <%= yield %>
    </div>
    <div class="column append-8 last">&nbsp;</div>
  </div>

</body>
</html>

app/views/questions/_question.html.erb
<%= div_for(question) do %>
  <%= question.question_text %>
<% end -%>

app/views/reviews/_review.html.erb
<%= content_tag_for(:tr, review) do %>
  <td><%= link_to review.title, review %></td>
  <td><%= review.start_on %></td>
  <td><%= review.end_on %></td>
<% end -%>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<%= link_to 'New Review', new_review_path %>

<table id="reviews"> 
  <tr>
    <th>Title</th>
    <th>Start On</th>
    <th>Complete By</th>
  </tr>

  <%= render @reviews %>

</table>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= simple_form_for @review do |f| %>
  <%= f.input :title %>
  <%= f.input :start_on, :start_year => Date.today.year %>
  <%= f.input :end_on, :start_year => Date.today.year %>
  <%= f.submit 'Create' %>
<% end -%>

app/views/reviews/show.html.erb
<h1><%= @review.title %></h1>

<%= render @review.questions %>

app/views/users/_form.html.erb
<%= f.input :username %>
<%= f.input :password, required: @user.new_record? %>
<%= f.input :first_name %>
<%= f.input :last_name %>

app/views/users/_user.html.erb
<%= content_tag_for(:tr, user) do %>
  <td><%= user.username %></td>
  <td><%= user.first_name %></td>
  <td><%= user.last_name %></td>
  <td><%= user.role %></td>
<% end -%>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to 'New User', new_user_path %>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Role</th>
    </tr>
  </thead>

  <%= render @users %>

</table>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit 'Create' %>
<% end -%>